obj-$(CONFIG_SND_SUN4I_CODEC) += sun4i-codec.o
obj-$(CONFIG_SND_SOC_SUN6I_AUDIO_CODEC) += sun6i-audio-codec.o
obj-$(CONFIG_SND_SOC_SUN6I_AUDIO_CODEC) += sun6i-audio-card.o
obj-$(CONFIG_SND_SOC_SUN6I_AUDIO_CODEC) += sun6i-audio-pcm.o
obj-$(CONFIG_SND_SOC_SUN6I_AUDIO_CODEC) += sun6i-codec.o

obj-$(CONFIG_SND_SUN4I_I2S) += sunxi-i2s.o

obj-$(CONFIG_SND_SUN4I_SPDIF) += sun4i-spdif.o
