obj-$(CONFIG_SND_SUN4I_CODEC) += sun4i-codec.o
obj-$(CONFIG_SND_SUN6I_CODEC) += sun6i-codec.o
obj-$(CONFIG_SND_SUN8I_CODEC) += sun8i-codec.o

obj-$(CONFIG_SND_SUN4I_I2S) += sunxi-i2s.o
obj-$(CONFIG_SND_SUN4I_I2S) += sun4i-dai.o

obj-$(CONFIG_SND_SUN4I_SPDIF) += sun4i-spdif.o
